import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
})

export const metadata = {
  title: "Rosemead Takeaway",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto.className} scroll-smooth`}>
      <body>
        {children}
      </body>
    </html>
  );
}
